export const CREW_CREATE_REQUEST = 'CREW_CREATE_REQUEST';
export const CREW_CREATE_SUCCESS = 'CREW_CREATE_SUCCESS';
export const CREW_CREATE_FAIL = 'CREW_CREATE_FAIL';
export const CREW_CREATE_RESET = 'CREW_CREATE_RESET';

export const CREW_LIST_REQUEST = 'CREW_LIST_REQUEST';
export const CREW_LIST_SUCCESS = 'CREW_LIST_SUCCESS';
export const CREW_LIST_FAIL = 'CREW_LIST_FAIL';



